Mise en place de Spring HTML Email avec le template engine Thymeleaf
Tests échec

Cause :
2020-08-12 13:35:36.509 ERROR 10032 --- [   scheduling-1]
org.thymeleaf.TemplateEngine             : [THYMELEAF][scheduling-1]
Exception processing template "templates/email-template.html": Error
resolving template [templates/email-template.html], template might not
exist or might not be accessible by any of the configured Template
Resolvers

org.thymeleaf.exceptions.TemplateInputException: Error resolving
template [templates/email-template.html], template might not exist or
might not be accessible by any of the configured Template Resolvers